<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('permissions')->insert(
            [
            [
                'group'=>'users',
                'title'=>'users_management_access',
            ],
            [
                'group'=>'users',
                'title'=>'users_access',
            ],
            [
                'group'=>'users',
                'title'=>'users_create',
            ],
            [
                'group'=>'users',
                'title'=>'users_read',
            ],
            [
                'group'=>'users',
                'title'=>'users_update',
            ],
            [
                'group'=>'users',
                'title'=>'users_delete',
            ],
            [
                'group'=>'users',
                'title'=>'roles_access',
            ],
            [
                'group'=>'users',
                'title'=>'roles_create',
            ],
            [
                'group'=>'users',
                'title'=>'roles_read',
            ],
            [
                'group'=>'users',
                'title'=>'roles_update',
            ],
            [
                'group'=>'users',
                'title'=>'roles_delete',
            ],
            [
                'group'=>'users',
                'title'=>'permissions_access',
            ],
            [
                'group'=>'users',
                'title'=>'permissions_create',
            ],
            [
                'group'=>'users',
                'title'=>'permissions_read',
            ],
            [
                'group'=>'users',
                'title'=>'permissions_update',
            ],
            [
                'group'=>'users',
                'title'=>'permissions_delete',
            ],
            [
                'group'=>'products',
                'title'=>'products_management_access',
            ],
            [
                'group'=>'products',
                'title'=>'products_access',
            ],
            [
                'group'=>'products',
                'title'=>'products_create',
            ],
            [
                'group'=>'products',
                'title'=>'products_delete',
            ],
            [
                'group'=>'products',
                'title'=>'products_read',
            ],
            [
                'group'=>'products',
                'title'=>'products_update',
            ],
            [
                'group'=>'products',
                'title'=>'product_units_access',
            ],
            [
                'group'=>'products',
                'title'=>'product_units_create',
            ],
            [
                'group'=>'products',
                'title'=>'product_units_delete',
            ],
            [
                'group'=>'products',
                'title'=>'product_units_read',
            ],
            [
                'group'=>'products',
                'title'=>'product_units_update',
            ],
            [
                'group'=>'products',
                'title'=>'product_categories_access',
            ],
            [
                'group'=>'products',
                'title'=>'product_categories_create',
            ],
            [
                'group'=>'products',
                'title'=>'product_categories_delete',
            ],
            [
                'group'=>'products',
                'title'=>'product_categories_read',
            ],
            [
                'group'=>'products',
                'title'=>'product_categories_update',
            ],
            [
                'group'=>'products',
                'title'=>'product_options_access',
            ],
            [
                'group'=>'products',
                'title'=>'product_options_create',
            ],
            [
                'group'=>'products',
                'title'=>'product_options_delete',
            ],
            [
                'group'=>'products',
                'title'=>'product_options_read',
            ],
            [
                'group'=>'products',
                'title'=>'product_options_update',
            ],
            [
                'group'=>'products',
                'title'=>'product_images_access',
            ],
            [
                'group'=>'products',
                'title'=>'product_images_create',
            ],
            [
                'group'=>'products',
                'title'=>'product_images_delete',
            ],
            [
                'group'=>'products',
                'title'=>'product_images_read',
            ],
            [
                'group'=>'products',
                'title'=>'product_images_update',
            ],
        ]);

    }
}
